KNN

In [ ]:
# !pip install anvil-uplink

In [ ]:
import anvil.server

In [ ]:
anvil.server.connect("WRWT5LU4BZMBE6N35EAAVTBE-DDO6DZJV5U4LMNLE")

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import linear_model # for regression model
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [ ]:
# df = pd.read_csv("https://raw.githubusercontent.com/asel-ik/SupportingFiles/main/Tor_Vanc_Cal.csv")
df= pd.read_csv("https://raw.githubusercontent.com/asel-ik/SupportingFiles/main/Tor_Vanc_Cal.csv", delimiter=',', header=None, skiprows=1, names=['year','city','assets_debts','age','value'])

In [ ]:
df = df.dropna(axis = 0)

In [ ]:
df_train, df_test = train_test_split(df, test_size = 0.25)

In [ ]:
metrics_train = pd.DataFrame(df_train, columns = ["year", "age", "value"])
metrics_test = pd.DataFrame(df_test, columns = ["year", "age", "value"])

In [ ]:
target_train = pd.DataFrame(df_train, columns = ["city"])
target_test = pd.DataFrame(df_test, columns = ["city"])
target_test

city
1356             Calgary, Alberta
651   Vancouver, British Columbia
723   Vancouver, British Columbia
490              Toronto, Ontario
635   Vancouver, British Columbia
...                           ...
1093             Calgary, Alberta
843   Vancouver, British Columbia
701   Vancouver, British Columbia
933   Vancouver, British Columbia
100              Toronto, Ontario

[262 rows x 1 columns]

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 4)

In [ ]:
knn.fit(metrics_train, target_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=4)

In [ ]:
predictions = knn.predict(metrics_test)

In [ ]:
print(confusion_matrix(target_test, predictions))

[[28 20 18]
 [30 50 27]
 [35 31 23]]


In [ ]:
print(classification_report(target_test, predictions))

                             precision    recall  f1-score   support

           Calgary, Alberta       0.30      0.42      0.35        66
           Toronto, Ontario       0.50      0.47      0.48       107
Vancouver, British Columbia       0.34      0.26      0.29        89

                   accuracy                           0.39       262
                  macro avg       0.38      0.38      0.38       262
               weighted avg       0.39      0.39      0.38       262



In [ ]:
@anvil.server.callable
def predict_city(year: int, age: int, value: int):
  classification = knn.predict([[year, age, value]])
  return (classification.astype(str))

In [ ]:
anvil.server.wait_forever()

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:561: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


KeyboardInterrupt: ignored